# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os
import unittest
from tests.http_response_catcher import HttpResponseCatcher
from akoyaapisv240.configuration import Configuration, Environment
from akoyaapisv240.akoyaapisv_240_client import Akoyaapisv240Client
from akoyaapisv240.http.auth.oauth_2 import AuthorizationCodeAuthCredentials


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = Akoyaapisv240Client(config=cls.config)

    @staticmethod
    def create_configuration():
        environment = os.getenv('AKOYAAPISV_240_ENVIRONMENT')
        oauth_client_id = os.getenv('AKOYAAPISV_240_OAUTH_CLIENT_ID')
        oauth_client_secret = os.getenv('AKOYAAPISV_240_OAUTH_CLIENT_SECRET')
        oauth_redirect_uri = os.getenv('AKOYAAPISV_240_OAUTH_REDIRECT_URI')

        if environment is not None:
            environment = Environment[environment.upper()]
        authorization_code_auth_credentials=None
        if (oauth_client_id is not None
                and oauth_client_secret is not None
                and oauth_redirect_uri is not None):
            authorization_code_auth_credentials=AuthorizationCodeAuthCredentials(
                oauth_client_id=oauth_client_id,
                oauth_client_secret=oauth_client_secret,
                oauth_redirect_uri=oauth_redirect_uri)


        config = Configuration(http_call_back=HttpResponseCatcher())
        return config.clone_with(
            authorization_code_auth_credentials=authorization_code_auth_credentials,
            environment=environment)

