# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from akoyaapisv240.models.annuity_account_info import AnnuityAccountInfo
from akoyaapisv240.models.annuity_balance import AnnuityBalance
from akoyaapisv240.models.annuity_balance_info import AnnuityBalanceInfo
from akoyaapisv240.models.deposit_account_info import DepositAccountInfo
from akoyaapisv240.models.deposit_balance import DepositBalance
from akoyaapisv240.models.deposit_balance_info import DepositBalanceInfo
from akoyaapisv240.models.deposit_transaction_info import DepositTransactionInfo
from akoyaapisv240.models.insurance_account_info import InsuranceAccountInfo
from akoyaapisv240.models.insurance_balance import InsuranceBalance
from akoyaapisv240.models.insurance_balance_info import InsuranceBalanceInfo
from akoyaapisv240.models.insurance_transaction_info import InsuranceTransactionInfo
from akoyaapisv240.models.investment_account_info import InvestmentAccountInfo
from akoyaapisv240.models.investment_balance import InvestmentBalance
from akoyaapisv240.models.investment_balance_info import InvestmentBalanceInfo
from akoyaapisv240.models.investment_transaction_info import InvestmentTransactionInfo
from akoyaapisv240.models.loan_account_info import LoanAccountInfo
from akoyaapisv240.models.loan_balance import LoanBalance
from akoyaapisv240.models.loan_balance_info import LoanBalanceInfo
from akoyaapisv240.models.loan_transaction_info import LoanTransactionInfo
from akoyaapisv240.models.loc_account_info import LocAccountInfo
from akoyaapisv240.models.loc_balance import LocBalance
from akoyaapisv240.models.loc_balance_info import LocBalanceInfo
from akoyaapisv240.models.loc_transaction_info import LocTransactionInfo
from apimatic_core.types.union_types.any_of import AnyOf
from apimatic_core.types.union_types.leaf_type import LeafType
from apimatic_core.types.union_types.union_type_context import UnionTypeContext as Context


class UnionTypeLookUp:

    """The `UnionTypeLookUp` class serves as a utility class for 
    storing and managing type combinator templates.It acts as a container for the templates 
    used in handling various data types within the application.

    """
    _templates = {
        'AkoyaAccountInfoProductAccounts': AnyOf(
            [
                LeafType(DepositAccountInfo),
                LeafType(LoanAccountInfo),
                LeafType(LocAccountInfo),
                LeafType(InvestmentAccountInfo),
                LeafType(InsuranceAccountInfo),
                LeafType(AnnuityAccountInfo)
            ],
            Context.create(
               is_array=True,
               is_optional=True
            )
        ),
        'BalancesAccounts': AnyOf(
            [
                LeafType(DepositBalance),
                LeafType(LoanBalance),
                LeafType(LocBalance),
                LeafType(InvestmentBalance),
                LeafType(InsuranceBalance),
                LeafType(AnnuityBalance)
            ],
            Context.create(
               is_array=True,
               is_optional=True
            )
        ),
        'InvestmentsDetailsAccounts': AnyOf(
            [
                LeafType(InvestmentBalanceInfo),
                LeafType(DepositBalanceInfo),
                LeafType(LoanBalanceInfo),
                LeafType(LocBalanceInfo),
                LeafType(InsuranceBalanceInfo),
                LeafType(AnnuityBalanceInfo)
            ],
            Context.create(
               is_array=True,
               is_optional=True
            )
        ),
        'TransactionsEntityTransactions': AnyOf(
            [
                LeafType(DepositTransactionInfo),
                LeafType(LoanTransactionInfo),
                LeafType(LocTransactionInfo),
                LeafType(InvestmentTransactionInfo),
                LeafType(InsuranceTransactionInfo)
            ],
            Context.create(
               is_array=True,
               is_optional=True
            )
        )
    }

    @staticmethod
    def get(name):
        return UnionTypeLookUp._templates[name]

