# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AccountInfoStatus(object):

    """Implementation of the 'AccountInfoStatus' enum.

    The status of an account.

    Attributes:
        OPEN: The enum member of type str.
        CLOSED: The enum member of type str.
        PENDINGOPEN: The enum member of type str.
        PENDINGCLOSE: The enum member of type str.
        DELINQUENT: The enum member of type str.
        PAID: The enum member of type str.
        NEGATIVECURRENTBALANCE: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    OPEN = 'OPEN'

    CLOSED = 'CLOSED'

    PENDINGOPEN = 'PENDINGOPEN'

    PENDINGCLOSE = 'PENDINGCLOSE'

    DELINQUENT = 'DELINQUENT'

    PAID = 'PAID'

    NEGATIVECURRENTBALANCE = 'NEGATIVECURRENTBALANCE'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
