# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AssetClass(object):

    """Implementation of the 'AssetClass' enum.

    Attributes:
        DOMESTICBOND: The enum member of type str.
        INTLBOND: The enum member of type str.
        LARGESTOCK: The enum member of type str.
        SMALLSTOCK: The enum member of type str.
        INTLSTOCK: The enum member of type str.
        MONEYMARKET: The enum member of type str.
        OTHER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    DOMESTICBOND = 'DOMESTICBOND'

    INTLBOND = 'INTLBOND'

    LARGESTOCK = 'LARGESTOCK'

    SMALLSTOCK = 'SMALLSTOCK'

    INTLSTOCK = 'INTLSTOCK'

    MONEYMARKET = 'MONEYMARKET'

    OTHER = 'OTHER'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
