# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DebitCreditMemo(object):

    """Implementation of the 'DebitCreditMemo' enum.

    Akoya will ensure that this is correctly populated with one of DEBIT or
    CREDIT and matches the sign of the status field.

    Attributes:
        DEBIT: The enum member of type str.
        CREDIT: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    DEBIT = 'DEBIT'

    CREDIT = 'CREDIT'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
