# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DebtClass(object):

    """Implementation of the 'DebtClass' enum.

    Classification of debt

    Attributes:
        TREASURY: The enum member of type str.
        MUNICIPAL: The enum member of type str.
        CORPORATE: The enum member of type str.
        OTHER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    TREASURY = 'TREASURY'

    MUNICIPAL = 'MUNICIPAL'

    CORPORATE = 'CORPORATE'

    OTHER = 'OTHER'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
