# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IncomeType(object):

    """Implementation of the 'IncomeType' enum.

    Type of investment income. CGLONG (capital gains-long term), CGSHORT
    (capital gains-short term), MISC.

    Attributes:
        CGLONG: The enum member of type str.
        CGSHORT: The enum member of type str.
        MISC: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    CGLONG = 'CGLONG'

    CGSHORT = 'CGSHORT'

    MISC = 'MISC'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
