# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InsuranceTransactionType(object):

    """Implementation of the 'InsuranceTransactionType' enum.

    InsuranceTransaction Type

    Attributes:
        PAYMENT: The enum member of type str.
        FEE: The enum member of type str.
        ADJUSTMENT: The enum member of type str.
        INTEREST: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    PAYMENT = 'PAYMENT'

    FEE = 'FEE'

    ADJUSTMENT = 'ADJUSTMENT'

    INTEREST = 'INTEREST'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
