# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InteractionType(object):

    """Implementation of the 'InteractionType' enum.

    Attributes:
        USER: The enum member of type str.
        BATCH: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    USER = 'user'

    BATCH = 'batch'

