# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InvestmentBalanceType(object):

    """Implementation of the 'InvestmentBalanceType' enum.

    The type of an investment balance. AMOUNT or PERCENTAGE.

    Attributes:
        AMOUNT: The enum member of type str.
        PERCENTAGE: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    AMOUNT = 'AMOUNT'

    PERCENTAGE = 'PERCENTAGE'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
