# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MediaType(object):

    """Implementation of the 'MediaType' enum.

    Attributes:
        ENUM_APPLICATIONJSON: The enum member of type str.
        ENUM_APPLICATIONPDF: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    ENUM_APPLICATIONJSON = 'application/json'

    ENUM_APPLICATIONPDF = 'application/pdf'

