# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MonthAbbreviation(object):

    """Implementation of the 'Month Abbreviation' enum.

    Month

    Attributes:
        JAN: The enum member of type str.
        FEB: The enum member of type str.
        MAR: The enum member of type str.
        APR: The enum member of type str.
        MAY: The enum member of type str.
        JUN: The enum member of type str.
        JUL: The enum member of type str.
        AUG: The enum member of type str.
        SEP: The enum member of type str.
        OCT: The enum member of type str.
        NOV: The enum member of type str.
        DEC: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    JAN = 'JAN'

    FEB = 'FEB'

    MAR = 'MAR'

    APR = 'APR'

    MAY = 'MAY'

    JUN = 'JUN'

    JUL = 'JUL'

    AUG = 'AUG'

    SEP = 'SEP'

    OCT = 'OCT'

    NOV = 'NOV'

    DEC = 'DEC'

