# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OauthScope(object):

    """Implementation of the 'OAuth Scope' enum.

    OAuth 2 scopes supported by the API

    Attributes:
        OPENID: OpenID Connect authentication
        PROFILE: Access to user profile information
        OFFLINE_ACCESS: Request refresh tokens for offline access

    """
    OPENID = 'openid'

    PROFILE = 'profile'

    OFFLINE_ACCESS = 'offline_access'

