# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderDuration(object):

    """Implementation of the 'OrderDuration' enum.

    This order is good for DAY, GOODTILLCANCEL, IMMEDIATE

    Attributes:
        DAY: The enum member of type str.
        GOODTILLCANCEL: The enum member of type str.
        IMMEDIATE: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    DAY = 'DAY'

    GOODTILLCANCEL = 'GOODTILLCANCEL'

    IMMEDIATE = 'IMMEDIATE'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
