# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PeriodCertainGuarantee(object):

    """Implementation of the 'PeriodCertainGuarantee' enum.

    Attributes:
        ENUM_NO PERIOD CERTAIN: The enum member of type str.
        ENUM_5YEAR: The enum member of type str.
        ENUM_10YEAR: The enum member of type str.
        ENUM_20YEAR: The enum member of type str.
        ENUM_30YEAR: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    ENUM_NO_PERIOD_CERTAIN = 'NO PERIOD CERTAIN'

    ENUM_5YEAR = '5-YEAR'

    ENUM_10YEAR = '10-YEAR'

    ENUM_20YEAR = '20-YEAR'

    ENUM_30YEAR = '30-YEAR'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
