# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SaleTermType(object):

    """Implementation of the 'Sale Term Type' enum.

    Long or short term. Used by Form 1099-B

    Attributes:
        LONG: The enum member of type str.
        SHORT: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    LONG = 'LONG'

    SHORT = 'SHORT'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
