# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Secured(object):

    """Implementation of the 'Secured' enum.

    How the option is secured

    Attributes:
        COVERED: The enum member of type str.
        NAKED: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    COVERED = 'COVERED'

    NAKED = 'NAKED'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
