# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SecurityType(object):

    """Implementation of the 'SecurityType' enum.

    Attributes:
        STOCK: The enum member of type str.
        MUTUALFUND: The enum member of type str.
        DEBT: The enum member of type str.
        OPTION: The enum member of type str.
        SWEEP: The enum member of type str.
        OTHER: The enum member of type str.
        BOND: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    STOCK = 'STOCK'

    MUTUALFUND = 'MUTUALFUND'

    DEBT = 'DEBT'

    OPTION = 'OPTION'

    SWEEP = 'SWEEP'

    OTHER = 'OTHER'

    BOND = 'BOND'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
