# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubAccountFund(object):

    """Implementation of the 'SubAccountFund' enum.

    From which account money came in.

    Attributes:
        CASH: The enum member of type str.
        MARGIN: The enum member of type str.
        SHORT: The enum member of type str.
        OTHERS: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    CASH = 'CASH'

    MARGIN = 'MARGIN'

    SHORT = 'SHORT'

    OTHERS = 'OTHERS'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
