# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TransferAction(object):

    """Implementation of the 'TransferAction' enum.

    Transfer direction.

    Attributes:
        IN: The enum member of type str.
        OUT: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    IN = 'IN'

    OUT = 'OUT'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
