# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeDataType(object):

    """Implementation of the 'Type Data Type' enum.

    Specify which data type is requested using TaxDataTypeQuery parameter, to
    receive 'JSON' formatted tax data in `forms` property or PDF-formatted tax
    data encoded as Base64 in `pdf` property ('BASE64_PDF'). In TaxStatement
    response entity indicates which tax data property was returned

    Attributes:
        BASE64_PDF: The enum member of type str.
        JSON: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    BASE64_PDF = 'BASE64_PDF'

    JSON = 'JSON'

