# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Version(object):

    """Implementation of the 'Version' enum.

    Attributes:
        V2: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    V2 = 'v2'

