# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AccountHolderEntityRelationshipEnum(object):

    """Implementation of the 'AccountHolderEntityRelationship' enum.

    Customer's relationship to the account

    Attributes:
        PRIMARY: The enum member of type str.
        JOINT: The enum member of type str.
        AUTHORIZED_USER: The enum member of type str.

    """
    PRIMARY = 'PRIMARY'

    JOINT = 'JOINT'

    AUTHORIZED_USER = 'AUTHORIZED_USER'

