# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AnnuityAccountPaymentFrequency(object):

    """Implementation of the 'AnnuityAccountPaymentFrequency' enum.

    Attributes:
        ANNUALLY: The enum member of type str.
        QUARTERLY: The enum member of type str.
        MONTHLY: The enum member of type str.
        WEEKLY: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    ANNUALLY = 'ANNUALLY'

    QUARTERLY = 'QUARTERLY'

    MONTHLY = 'MONTHLY'

    WEEKLY = 'WEEKLY'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
