# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AnnunityProductType(object):

    """Implementation of the 'AnnunityProductType' enum.

    Attributes:
        CURRENCY: The enum member of type str.
        SHARES: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    CURRENCY = 'CURRENCY'

    SHARES = 'SHARES'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
