# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BalanceType(object):

    """Implementation of the 'BalanceType' enum.

    ASSET (positive transaction amount increases balance), LIABILITY (positive
    transaction amount decreases balance)

    Attributes:
        ASSET: The enum member of type str.
        LIABILITY: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    ASSET = 'ASSET'

    LIABILITY = 'LIABILITY'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
