# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CallType(object):

    """Implementation of the 'CallType' enum.

    Type of next call

    Attributes:
        CALL: The enum member of type str.
        PUT: The enum member of type str.
        PREFUND: The enum member of type str.
        MATURITY: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    CALL = 'CALL'

    PUT = 'PUT'

    PREFUND = 'PREFUND'

    MATURITY = 'MATURITY'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
