# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ContentType(object):

    """Implementation of the 'ContentType' enum.

    Attributes:
        ENUM_APPLICATIONPDF: The enum member of type str.
        ENUM_IMAGEGIF: The enum member of type str.
        ENUM_IMAGEJPEG: The enum member of type str.
        ENUM_IMAGETIFF: The enum member of type str.
        ENUM_IMAGEPNG: The enum member of type str.
        ENUM_APPLICATIONJSON: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    ENUM_APPLICATIONPDF = 'application/pdf'

    ENUM_IMAGEGIF = 'image/gif'

    ENUM_IMAGEJPEG = 'image/jpeg'

    ENUM_IMAGETIFF = 'image/tiff'

    ENUM_IMAGEPNG = 'image/png'

    ENUM_APPLICATIONJSON = 'application/json'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
