# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CouponMatureFrequency(object):

    """Implementation of the 'CouponMatureFrequency' enum.

    When coupons mature

    Attributes:
        MONTHLY: The enum member of type str.
        QUARTERLY: The enum member of type str.
        SEMIANNUAL: The enum member of type str.
        ANNUAL: The enum member of type str.
        OTHER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    MONTHLY = 'MONTHLY'

    QUARTERLY = 'QUARTERLY'

    SEMIANNUAL = 'SEMIANNUAL'

    ANNUAL = 'ANNUAL'

    OTHER = 'OTHER'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
