# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ExpiredOptionType(object):

    """Implementation of the 'Expired Option Type' enum.

    To indicate gain or loss resulted from option expiration. If salesPrice
    (1d, proceeds) is zero, use PURCHASED. If costBasis (1e) is zero, use
    GRANTED

    Attributes:
        GRANTED: The enum member of type str.
        PURCHASED: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    GRANTED = 'GRANTED'

    PURCHASED = 'PURCHASED'

