# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class HoldingType(object):

    """Implementation of the 'HoldingType' enum.

    Attributes:
        STOCK: The enum member of type str.
        BOND: The enum member of type str.
        MUTUALFUND: The enum member of type str.
        CD: The enum member of type str.
        ANNUITY: The enum member of type str.
        OPTION: The enum member of type str.
        OTHER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    STOCK = 'STOCK'

    BOND = 'BOND'

    MUTUALFUND = 'MUTUALFUND'

    CD = 'CD'

    ANNUITY = 'ANNUITY'

    OPTION = 'OPTION'

    OTHER = 'OTHER'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
