# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class HttpMethod(object):

    """Implementation of the 'HttpMethod' enum.

    HTTP Method to use for the request

    Attributes:
        GET: The enum member of type str.
        POST: The enum member of type str.
        PATCH: The enum member of type str.
        DELETE: The enum member of type str.
        PUT: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    GET = 'GET'

    POST = 'POST'

    PATCH = 'PATCH'

    DELETE = 'DELETE'

    PUT = 'PUT'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
