# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InteractionTypeEnum(object):

    """Implementation of the 'InteractionType' enum.

    Attributes:
        USER: The enum member of type str.
        BATCH: The enum member of type str.

    """
    USER = 'user'

    BATCH = 'batch'

