# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InvestmentTransactionSecurityIdType(object):

    """Implementation of the 'InvestmentTransactionSecurityIdType' enum.

    Security identifier type.

    Attributes:
        BUSIP: The enum member of type str.
        ISIN: The enum member of type str.
        SEDOL: The enum member of type str.
        SICC: The enum member of type str.
        VALOR: The enum member of type str.
        WKN: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    BUSIP = 'BUSIP'

    ISIN = 'ISIN'

    SEDOL = 'SEDOL'

    SICC = 'SICC'

    VALOR = 'VALOR'

    WKN = 'WKN'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
