# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LoanPaymentFrequency(object):

    """Implementation of the 'LoanPaymentFrequency' enum.

    Attributes:
        WEEKLY: The enum member of type str.
        BIWEEKLY: The enum member of type str.
        TWICEMONTHLY: The enum member of type str.
        MONTHLY: The enum member of type str.
        FOURWEEKS: The enum member of type str.
        BIMONTHLY: The enum member of type str.
        QUARTERLY: The enum member of type str.
        SEMIANNUALLY: The enum member of type str.
        ANNUALLY: The enum member of type str.
        OTHER: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    WEEKLY = 'WEEKLY'

    BIWEEKLY = 'BIWEEKLY'

    TWICEMONTHLY = 'TWICEMONTHLY'

    MONTHLY = 'MONTHLY'

    FOURWEEKS = 'FOURWEEKS'

    BIMONTHLY = 'BIMONTHLY'

    QUARTERLY = 'QUARTERLY'

    SEMIANNUALLY = 'SEMIANNUALLY'

    ANNUALLY = 'ANNUALLY'

    OTHER = 'OTHER'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
