# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LocationTypeEnum(object):

    """Implementation of the 'Location type' enum.

    The location type of an address

    Attributes:
        BUSINESS: The enum member of type str.
        HOME: The enum member of type str.
        MAILING: The enum member of type str.

    """
    BUSINESS = 'BUSINESS'

    HOME = 'HOME'

    MAILING = 'MAILING'

