# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MediaTypeEnum(object):

    """Implementation of the 'MediaType' enum.

    Attributes:
        ENUM_APPLICATIONJSON: The enum member of type str.
        ENUM_APPLICATIONPDF: The enum member of type str.

    """
    ENUM_APPLICATIONJSON = 'application/json'

    ENUM_APPLICATIONPDF = 'application/pdf'

