# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ModeEnum(object):

    """Implementation of the 'Mode' enum.

    Indicates format of returned data.
    'raw' = provider-specific;
    'standard' = FDX-aligned values (BETA)

    Attributes:
        RAW: The enum member of type str.
        STANDARD: The enum member of type str.

    """
    RAW = 'raw'

    STANDARD = 'standard'

