# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PhoneType(object):

    """Implementation of the 'Phone type' enum.

    Attributes:
        HOME: The enum member of type str.
        BUSINESS: The enum member of type str.
        CELL: The enum member of type str.
        FAX: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    HOME = 'HOME'

    BUSINESS = 'BUSINESS'

    CELL = 'CELL'

    FAX = 'FAX'

