# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PolicyPremiumTerm(object):

    """Implementation of the 'PolicyPremiumTerm' enum.

    he payment term for the premium. MONTHLY or ANNUAL.

    Attributes:
        MONTHLY: The enum member of type str.
        ANNUAL: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    MONTHLY = 'MONTHLY'

    ANNUAL = 'ANNUAL'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
