# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PositionType(object):

    """Implementation of the 'positionType' enum.

    LONG, SHORT.

    Attributes:
        LONG: The enum member of type str.
        SHORT: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    LONG = 'LONG'

    SHORT = 'SHORT'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
