# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SaleProceedsType(object):

    """Implementation of the 'Sale Proceeds Type' enum.

    Gross or net proceeds. Used by Form 1099-B

    Attributes:
        GROSS: The enum member of type str.
        NET: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    GROSS = 'GROSS'

    NET = 'NET'

