# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TaxPartyTypeEnum(object):

    """Implementation of the 'Tax Party Type' enum.

    Type of issuer or recipient legal entity, as "BUSINESS" or "INDIVIDUAL".
    Commonly BUSINESS for issuer and INDIVIDUAL for recipient

    Attributes:
        BUSINESS: The enum member of type str.
        INDIVIDUAL: The enum member of type str.

    """
    BUSINESS = 'BUSINESS'

    INDIVIDUAL = 'INDIVIDUAL'

