# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from akoyaapisv240.api_helper import APIHelper


class Telephone(object):

    """Implementation of the 'Telephone' model.

    Attributes:
        number (str): The model property of type str.
        mtype (PhoneType): The model property of type PhoneType.
        country (str): Country calling codes defined by ITU-T recommendations
            E.123 and E.164
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "number": 'number',
        "mtype": 'type',
        "country": 'country'
    }

    _optionals = [
        'number',
        'mtype',
        'country',
    ]

    def __init__(self,
                 number=APIHelper.SKIP,
                 mtype=APIHelper.SKIP,
                 country=APIHelper.SKIP,
                 additional_properties=None):
        """Constructor for the Telephone class"""

        # Initialize members of the class
        if number is not APIHelper.SKIP:
            self.number = number 
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype 
        if country is not APIHelper.SKIP:
            self.country = country 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        number = dictionary.get("number") if dictionary.get("number") else APIHelper.SKIP
        mtype = dictionary.get("type") if dictionary.get("type") else APIHelper.SKIP
        country = dictionary.get("country") if dictionary.get("country") else APIHelper.SKIP
        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items() if k not in cls._names.values()},
            unboxing_function=lambda value: value)
        # Return an object of this model
        return cls(number,
                   mtype,
                   country,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'number={(self.number if hasattr(self, "number") else None)!r}, '
                f'mtype={(self.mtype if hasattr(self, "mtype") else None)!r}, '
                f'country={(self.country if hasattr(self, "country") else None)!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'number={(self.number if hasattr(self, "number") else None)!s}, '
                f'mtype={(self.mtype if hasattr(self, "mtype") else None)!s}, '
                f'country={(self.country if hasattr(self, "country") else None)!s}, '
                f'additional_properties={self.additional_properties!s})')
