# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TelephoneNumberType(object):

    """Implementation of the 'Telephone Number Type' enum.

    Type of phone number: HOME, BUSINESS, CELL, FAX

    Attributes:
        BUSINESS: The enum member of type str.
        CELL: The enum member of type str.
        FAX: The enum member of type str.
        HOME: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    BUSINESS = 'BUSINESS'

    CELL = 'CELL'

    FAX = 'FAX'

    HOME = 'HOME'

