# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TransationStatus(object):

    """Implementation of the 'TransationStatus' enum.

    AUTHORIZATION, MEMO, PENDING, or POSTED

    Attributes:
        PENDING: The enum member of type str.
        MEMO: The enum member of type str.
        POSTED: The enum member of type str.
        AUTHORIZATION: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    PENDING = 'PENDING'

    MEMO = 'MEMO'

    POSTED = 'POSTED'

    AUTHORIZATION = 'AUTHORIZATION'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
