# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TransactionReason(object):

    """Implementation of the 'TransactionReason' enum.

    Reason for this transaction; CALL (the debt was called), SELL (the debt
    was sold), MATURITY (the debt reached maturity)

    Attributes:
        CALL: The enum member of type str.
        SELL: The enum member of type str.
        MATURITY: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    CALL = 'CALL'

    SELL = 'SELL'

    MATURITY = 'MATURITY'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return True if value else False 
