# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.configurations.global_configuration import GlobalConfiguration
from apimatic_core.decorators.lazy_property import LazyProperty
from akoyaapisv240.configuration import Configuration
from akoyaapisv240.controllers.base_controller import BaseController
from akoyaapisv240.configuration import Environment
from akoyaapisv240.http.auth.oauth_2 import Oauth2
from akoyaapisv240.controllers.account_information_controller\
    import AccountInformationController
from akoyaapisv240.controllers.balances_controller import BalancesController
from akoyaapisv240.controllers.customers_controller import CustomersController
from akoyaapisv240.controllers.investments_controller\
    import InvestmentsController
from akoyaapisv240.controllers.payments_controller import PaymentsController
from akoyaapisv240.controllers.statements_controller\
    import StatementsController
from akoyaapisv240.controllers.tax_beta_controller import TaxBetaController
from akoyaapisv240.controllers.transactions_controller\
    import TransactionsController
from akoyaapisv240.controllers.oauth_authorization_controller\
    import OauthAuthorizationController


class Akoyaapisv240Client(object):
    @LazyProperty
    def account_information(self):
        return AccountInformationController(self.global_configuration)

    @LazyProperty
    def balances(self):
        return BalancesController(self.global_configuration)

    @LazyProperty
    def customers(self):
        return CustomersController(self.global_configuration)

    @LazyProperty
    def investments(self):
        return InvestmentsController(self.global_configuration)

    @LazyProperty
    def payments(self):
        return PaymentsController(self.global_configuration)

    @LazyProperty
    def statements(self):
        return StatementsController(self.global_configuration)

    @LazyProperty
    def tax_beta(self):
        return TaxBetaController(self.global_configuration)

    @LazyProperty
    def transactions(self):
        return TransactionsController(self.global_configuration)

    @LazyProperty
    def oauth_authorization(self):
        return OauthAuthorizationController(self.global_configuration)

    @property
    def acg_auth(self):
        return self.auth_managers['acgAuth']

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None,
                 logging_configuration=None, environment=Environment.SANDBOX,
                 authorization_code_auth_credentials=None, config=None):
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            logging_configuration=logging_configuration,
            environment=environment,
            authorization_code_auth_credentials=authorization_code_auth_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseController.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseController.user_agent(), BaseController.user_agent_parameters())

        self.auth_managers = {key: None for key in ['acgAuth']}
        self.auth_managers['acgAuth'] = Oauth2(
            self.config.authorization_code_auth_credentials,
            self.global_configuration)
        self.global_configuration = self.global_configuration.auth_managers(self.auth_managers)

