name: Run Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Create env
      run: |
        echo "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" >> .env
        echo "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> .env
        echo "OAUTH_REDIRECT_URI=${{ secrets.OAUTH_REDIRECT_URI }}" >> .env
        echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
        echo "TEST_USERNAME=${{ secrets.TEST_USERNAME }}" >> .env
        echo "TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}" >> .env
        echo "TAX_USERNAME=${{ secrets.TAX_USERNAME }}" >> .env
        echo "TAX_PASSWORD=${{ secrets.TAX_PASSWORD }}" >> .env
        echo "CONNECTOR=${{ secrets.CONNECTOR }}" >> .env
        echo "STATE=${{ secrets.STATE }}" >> .env
        echo "RETURN_URL=${{ secrets.RETURN_URL }}" >> .env
        echo "AKOYA_PROVIDER_ID=${{ secrets.AKOYA_PROVIDER_ID }}" >> .env
        echo "AKOYA_API_VERSION=${{ secrets.AKOYA_API_VERSION }}" >> .env
        echo "STATEMENT_ACCOUNT_ID=${{ secrets.STATEMENT_ACCOUNT_ID }}" >> .env
        echo "TAXLOT_ACCOUNT_ID=${{ secrets.TAXLOT_ACCOUNT_ID }}" >> .env
        echo "HOLDING_ID=${{ secrets.HOLDING_ID }}" >> .env
        echo "STATEMENT_ID=${{ secrets.STATEMENT_ID }}" >> .env
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Running E2E tests
      run: pytest --reruns=3
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/